version: '3.8'

services:
  dind:
    image: docker:24-dind
    privileged: true  # Allows Docker commands inside the container
    container_name: dind_service
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs:/certs/client
      - docker-data:/var/lib/docker
    networks:
      - jenkins_net

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins_service
    user: root
    ports:
      - "8080:8080"  # Jenkins Web UI
      - "50000:50000"  # Jenkins agent communication
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker-certs:/certs/client:ro
    networks:
      - jenkins_net

networks:
  jenkins_net:

volumes:
  jenkins_home:
  docker-data:
  docker-certs:
