services:
  dind:
    image: docker:24-dind
    privileged: true
    container_name: dind_service
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - docker-data:/var/lib/docker
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_net

  jenkins:
    build: ./jenkins
    container_name: jenkins_service
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_net

networks:
  jenkins_net:

volumes:
  jenkins_home:
  docker-data:
